// <auto-generated />
using System;
using DotnetVoyager.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetVoyager.DAL.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251025211604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DotnetVoyager.DAL.Entities.AnalysisStatus", b =>
                {
                    b.Property<string>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZipStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnalysisId");

                    b.ToTable("AnalysisStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
