// <auto-generated />
using System;
using DotnetVoyager.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetVoyager.DAL.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251124105951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DotnetVoyager.DAL.Entities.AnalysisStatus", b =>
                {
                    b.Property<string>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnalysisId");

                    b.HasIndex("LastUpdatedUtc");

                    b.ToTable("AnalysisStatuses");
                });

            modelBuilder.Entity("DotnetVoyager.DAL.Entities.AnalysisStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId", "StepName")
                        .IsUnique();

                    b.HasIndex("Status", "AnalysisId");

                    b.ToTable("AnalysisSteps");
                });

            modelBuilder.Entity("DotnetVoyager.DAL.Entities.AnalysisStep", b =>
                {
                    b.HasOne("DotnetVoyager.DAL.Entities.AnalysisStatus", "Analysis")
                        .WithMany("Steps")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("DotnetVoyager.DAL.Entities.AnalysisStatus", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
